# Generated by Django 3.1.7 on 2021-04-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentapp', '0003_remove_inputdata_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inputdata',
        ),
    ]
