# Generated by Django 3.1.7 on 2021-04-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentapp', '0005_inputdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdata',
            name='slider',
            field=models.TextField(default=0),
        ),
    ]
