# Generated by Django 3.1.7 on 2021-04-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentapp', '0006_inputdata_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputdata',
            old_name='content',
            new_name='textdata',
        ),
        migrations.AddField(
            model_name='inputdata',
            name='date',
            field=models.DateField(default='2021-03-03'),
        ),
    ]
