# Generated by Django 3.1.7 on 2021-04-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentapp', '0007_auto_20210403_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputdata',
            name='date',
        ),
    ]
